using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using NBA.Model;

namespace NBA.DAL
{
	public class NBAManagerDbContext : IdentityDbContext<AppUser>
	{
		public NBAManagerDbContext(DbContextOptions<NBAManagerDbContext> options) : base(options) { }

		public DbSet<Player> Players { get; set; }
		public DbSet<Team> Teams { get; set; }
		public DbSet<Position> Positions { get; set; }
		public DbSet<Country> Countries { get; set; }
		public DbSet<Venue> Venues { get; set; }
		public DbSet<Coach> Coaches { get; set; }
		public DbSet<Conference> Conferences { get; set; }
		public DbSet<PlayerAttachment> PlayerAttachments { get; set; }
		public DbSet<Game> Games { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Conference>().HasData(
				new Conference { ID = 1, Name = "Eastern Conference" },
				new Conference { ID = 2, Name = "Western Conference" }
			);
            modelBuilder.Entity<Position>().HasData(
				new Position { ID = 1, Name = "Point Guard (PG)" },
				new Position { ID = 2, Name = "Shooting Guard (SG)" },
				new Position { ID = 3, Name = "Small Forward (SF)" },
				new Position { ID = 4, Name = "Power Forward (PF)" },
				new Position { ID = 5, Name = "Center (C)" }
			);
			modelBuilder.Entity<Team>().HasData(
				new Team { ID = 1, Name = "Atlanta Hawks", VenueID = 1, ConferenceID = 1, Path = "/images/teams/1.png" },
				new Team { ID = 2, Name = "Boston Celtics", VenueID = 2, ConferenceID = 1, Path = "/images/teams/2.png" },
				new Team { ID = 3, Name = "Brooklyn Nets", VenueID = 3, ConferenceID = 1, Path = "/images/teams/3.png" },
				new Team { ID = 4, Name = "Charlotte Hornets", VenueID = 4, ConferenceID = 1, Path = "/images/teams/4.png" },
				new Team { ID = 5, Name = "Chicago Bulls", VenueID = 5, ConferenceID = 1, Path = "/images/teams/5.png" },
				new Team { ID = 6, Name = "Cleveland Cavaliers", VenueID = 6, ConferenceID = 1, Path = "/images/teams/6.png" },
				new Team { ID = 7, Name = "Dallas Mavericks", VenueID = 7, ConferenceID = 2, Path = "/images/teams/7.png" },
				new Team { ID = 8, Name = "Denver Nuggets", VenueID = 8, ConferenceID = 2, Path = "/images/teams/8.png" },
				new Team { ID = 9, Name = "Detroit Pistons", VenueID = 9, ConferenceID = 1, Path = "/images/teams/9.png" },
				new Team { ID = 10, Name = "Golden State Warriors", VenueID = 10, ConferenceID = 2, Path = "/images/teams/10.png" },
				new Team { ID = 11, Name = "Houston Rockets", VenueID = 11, ConferenceID = 2, Path = "/images/teams/11.png" },
				new Team { ID = 12, Name = "Indiana Pacers", VenueID = 12, ConferenceID = 1, Path = "/images/teams/12.png" },
				new Team { ID = 13, Name = "Los Angeles Clippers", VenueID = 13, ConferenceID = 2, Path = "/images/teams/13.png" },
				new Team { ID = 14, Name = "Los Angeles Lakers", VenueID = 14, ConferenceID = 2, Path = "/images/teams/14.png" },
				new Team { ID = 15, Name = "Memphis Grizzlies", VenueID = 15, ConferenceID = 2, Path = "/images/teams/15.png" },
				new Team { ID = 16, Name = "Miami Heat", VenueID = 16, ConferenceID = 1, Path = "/images/teams/16.png" },
				new Team { ID = 17, Name = "Milwaukee Bucks", VenueID = 17, ConferenceID = 1, Path = "/images/teams/17.png" },
				new Team { ID = 18, Name = "Minnesota Timberwolves", VenueID = 18, ConferenceID = 2, Path = "/images/teams/18.png" },
				new Team { ID = 19, Name = "New Orleans Pelicans", VenueID = 19, ConferenceID = 2, Path = "/images/teams/19.png" },
				new Team { ID = 20, Name = "New York Knicks", VenueID = 20, ConferenceID = 1, Path = "/images/teams/20.png" },
				new Team { ID = 21, Name = "Oklahoma City Thunder", VenueID = 21, ConferenceID = 2, Path = "/images/teams/21.png" },
				new Team { ID = 22, Name = "Orlando Magic", VenueID = 22, ConferenceID = 1, Path = "/images/teams/22.png" },
				new Team { ID = 23, Name = "Philadelphia 76ers", VenueID = 23, ConferenceID = 1, Path = "/images/teams/23.png" },
				new Team { ID = 24, Name = "Phoenix Suns", VenueID = 24, ConferenceID = 2, Path = "/images/teams/24.png" },
				new Team { ID = 25, Name = "Portland Trail Blazers", VenueID = 25, ConferenceID = 2, Path = "/images/teams/25.png" },
				new Team { ID = 26, Name = "Sacramento Kings", VenueID = 26, ConferenceID = 2, Path = "/images/teams/26.png" },
				new Team { ID = 27, Name = "San Antonio Spurs", VenueID = 27, ConferenceID = 2, Path = "/images/teams/27.png" },
				new Team { ID = 28, Name = "Toronto Raptors", VenueID = 28, ConferenceID = 1, Path = "/images/teams/28.png" },
				new Team { ID = 29, Name = "Utah Jazz", VenueID = 29, ConferenceID = 2, Path = "/images/teams/29.png" },
				new Team { ID = 30, Name = "Washington Wizards", VenueID = 30, ConferenceID = 1, Path = "/images/teams/30.png" }
			);

			modelBuilder.Entity<Venue>().HasData(
				new Venue { ID = 1, Name = "State Farm Arena", City = "Atlanta" },
				new Venue { ID = 2, Name = "TD Garden", City = "Boston" },
				new Venue { ID = 3, Name = "Barclays Center", City = "Brooklyn" },
				new Venue { ID = 4, Name = "Spectrum Center", City = "Charlotte" },
				new Venue { ID = 5, Name = "United Center", City = "Chicago" },
				new Venue { ID = 6, Name = "Rocket Mortgage FieldHouse", City = "Cleveland" },
				new Venue { ID = 7, Name = "American Airlines Center", City = "Dallas" },
				new Venue { ID = 8, Name = "Ball Arena", City = "Denver" },
				new Venue { ID = 9, Name = "Little Caesars Arena", City = "Detroit" },
				new Venue { ID = 10, Name = "Chase Center", City = "San Francisco" },
				new Venue { ID = 11, Name = "Toyota Center", City = "Houston" },
				new Venue { ID = 12, Name = "Gainbridge Fieldhouse", City = "Indianapolis" },
				new Venue { ID = 13, Name = "Crypto.com Arena", City = "Los Angeles" },
				new Venue { ID = 14, Name = "Crypto.com Arena", City = "Los Angeles" }, 
				new Venue { ID = 15, Name = "FedExForum", City = "Memphis" },
				new Venue { ID = 16, Name = "Kaseya Center", City = "Miami" },
				new Venue { ID = 17, Name = "Fiserv Forum", City = "Milwaukee" },
				new Venue { ID = 18, Name = "Target Center", City = "Minneapolis" },
				new Venue { ID = 19, Name = "Smoothie King Center", City = "New Orleans" },
				new Venue { ID = 20, Name = "Madison Square Garden", City = "New York" },
				new Venue { ID = 21, Name = "Paycom Center", City = "Oklahoma City" },
				new Venue { ID = 22, Name = "Amway Center", City = "Orlando" },
				new Venue { ID = 23, Name = "Wells Fargo Center", City = "Philadelphia" },
				new Venue { ID = 24, Name = "Footprint Center", City = "Phoenix" },
				new Venue { ID = 25, Name = "Moda Center", City = "Portland" },
				new Venue { ID = 26, Name = "Golden 1 Center", City = "Sacramento" },
				new Venue { ID = 27, Name = "AT&T Center", City = "San Antonio" },
				new Venue { ID = 28, Name = "Scotiabank Arena", City = "Toronto" },
				new Venue { ID = 29, Name = "Vivint Arena", City = "Salt Lake City" },
				new Venue { ID = 30, Name = "Capital One Arena", City = "Washington, D.C." }
			);

			modelBuilder.Entity<Country>().HasData(
				new Country { ID = 1, Name = "Afghanistan" },
				new Country { ID = 2, Name = "Albania" },
				new Country { ID = 3, Name = "Algeria" },
				new Country { ID = 4, Name = "Andorra" },
				new Country { ID = 5, Name = "Angola" },
				new Country { ID = 6, Name = "Antigua and Barbuda" },
				new Country { ID = 7, Name = "Argentina" },
				new Country { ID = 8, Name = "Armenia" },
				new Country { ID = 9, Name = "Australia" },
				new Country { ID = 10, Name = "Austria" },
				new Country { ID = 11, Name = "Azerbaijan" },
				new Country { ID = 12, Name = "Bahamas" },
				new Country { ID = 13, Name = "Bahrain" },
				new Country { ID = 14, Name = "Bangladesh" },
				new Country { ID = 15, Name = "Barbados" },
				new Country { ID = 16, Name = "Belarus" },
				new Country { ID = 17, Name = "Belgium" },
				new Country { ID = 18, Name = "Belize" },
				new Country { ID = 19, Name = "Benin" },
				new Country { ID = 20, Name = "Bhutan" },
				new Country { ID = 21, Name = "Bolivia" },
				new Country { ID = 22, Name = "Bosnia and Herzegovina" },
				new Country { ID = 23, Name = "Botswana" },
				new Country { ID = 24, Name = "Brazil" },
				new Country { ID = 25, Name = "Brunei" },
				new Country { ID = 26, Name = "Bulgaria" },
				new Country { ID = 27, Name = "Burkina Faso" },
				new Country { ID = 28, Name = "Burundi" },
				new Country { ID = 29, Name = "Cabo Verde" },
				new Country { ID = 30, Name = "Cambodia" },
				new Country { ID = 31, Name = "Cameroon" },
				new Country { ID = 32, Name = "Canada" },
				new Country { ID = 33, Name = "Central African Republic" },
				new Country { ID = 34, Name = "Chad" },
				new Country { ID = 35, Name = "Chile" },
				new Country { ID = 36, Name = "China" },
				new Country { ID = 37, Name = "Colombia" },
				new Country { ID = 38, Name = "Comoros" },
				new Country { ID = 39, Name = "Congo, Democratic Republic of the" },
				new Country { ID = 40, Name = "Congo, Republic of the" },
				new Country { ID = 41, Name = "Costa Rica" },
				new Country { ID = 42, Name = "Croatia" },
				new Country { ID = 43, Name = "Cuba" },
				new Country { ID = 44, Name = "Cyprus" },
				new Country { ID = 45, Name = "Czech Republic" },
				new Country { ID = 46, Name = "Denmark" },
				new Country { ID = 47, Name = "Djibouti" },
				new Country { ID = 48, Name = "Dominica" },
				new Country { ID = 49, Name = "Dominican Republic" },
				new Country { ID = 50, Name = "Ecuador" },
				new Country { ID = 51, Name = "Egypt" },
				new Country { ID = 52, Name = "El Salvador" },
				new Country { ID = 53, Name = "Equatorial Guinea" },
				new Country { ID = 54, Name = "Eritrea" },
				new Country { ID = 55, Name = "Estonia" },
				new Country { ID = 56, Name = "Eswatini" },
				new Country { ID = 57, Name = "Ethiopia" },
				new Country { ID = 58, Name = "Fiji" },
				new Country { ID = 59, Name = "Finland" },
				new Country { ID = 60, Name = "France" },
				new Country { ID = 61, Name = "Gabon" },
				new Country { ID = 62, Name = "Gambia" },
				new Country { ID = 63, Name = "Georgia" },
				new Country { ID = 64, Name = "Germany" },
				new Country { ID = 65, Name = "Ghana" },
				new Country { ID = 66, Name = "Greece" },
				new Country { ID = 67, Name = "Grenada" },
				new Country { ID = 68, Name = "Guatemala" },
				new Country { ID = 69, Name = "Guinea" },
				new Country { ID = 70, Name = "Guinea-Bissau" },
				new Country { ID = 71, Name = "Guyana" },
				new Country { ID = 72, Name = "Haiti" },
				new Country { ID = 73, Name = "Honduras" },
				new Country { ID = 74, Name = "Hungary" },
				new Country { ID = 75, Name = "Iceland" },
				new Country { ID = 76, Name = "India" },
				new Country { ID = 77, Name = "Indonesia" },
				new Country { ID = 78, Name = "Iran" },
				new Country { ID = 79, Name = "Iraq" },
				new Country { ID = 80, Name = "Ireland" },
				new Country { ID = 81, Name = "Israel" },
				new Country { ID = 82, Name = "Italy" },
				new Country { ID = 83, Name = "Jamaica" },
				new Country { ID = 84, Name = "Japan" },
				new Country { ID = 85, Name = "Jordan" },
				new Country { ID = 86, Name = "Kazakhstan" },
				new Country { ID = 87, Name = "Kenya" },
				new Country { ID = 88, Name = "Kiribati" },
				new Country { ID = 89, Name = "Korea, North" },
				new Country { ID = 90, Name = "Korea, South" },
				new Country { ID = 91, Name = "Kosovo" },
				new Country { ID = 92, Name = "Kuwait" },
				new Country { ID = 93, Name = "Kyrgyzstan" },
				new Country { ID = 94, Name = "Laos" },
				new Country { ID = 95, Name = "Latvia" },
				new Country { ID = 96, Name = "Lebanon" },
				new Country { ID = 97, Name = "Lesotho" },
				new Country { ID = 98, Name = "Liberia" },
				new Country { ID = 99, Name = "Libya" },
				new Country { ID = 100, Name = "Liechtenstein" },
				new Country { ID = 101, Name = "Lithuania" },
				new Country { ID = 102, Name = "Luxembourg" },
				new Country { ID = 103, Name = "Madagascar" },
				new Country { ID = 104, Name = "Malawi" },
				new Country { ID = 105, Name = "Malaysia" },
				new Country { ID = 106, Name = "Maldives" },
				new Country { ID = 107, Name = "Mali" },
				new Country { ID = 108, Name = "Malta" },
				new Country { ID = 109, Name = "Marshall Islands" },
				new Country { ID = 110, Name = "Mauritania" },
				new Country { ID = 111, Name = "Mauritius" },
				new Country { ID = 112, Name = "Mexico" },
				new Country { ID = 113, Name = "Micronesia" },
				new Country { ID = 114, Name = "Moldova" },
				new Country { ID = 115, Name = "Monaco" },
				new Country { ID = 116, Name = "Mongolia" },
				new Country { ID = 117, Name = "Montenegro" },
				new Country { ID = 118, Name = "Morocco" },
				new Country { ID = 119, Name = "Mozambique" },
				new Country { ID = 120, Name = "Myanmar" },
				new Country { ID = 121, Name = "Namibia" },
				new Country { ID = 122, Name = "Nauru" },
				new Country { ID = 123, Name = "Nepal" },
				new Country { ID = 124, Name = "Netherlands" },
				new Country { ID = 125, Name = "New Zealand" },
				new Country { ID = 126, Name = "Nicaragua" },
				new Country { ID = 127, Name = "Niger" },
				new Country { ID = 128, Name = "Nigeria" },
				new Country { ID = 129, Name = "North Macedonia" },
				new Country { ID = 130, Name = "Norway" },
				new Country { ID = 131, Name = "Oman" },
				new Country { ID = 132, Name = "Pakistan" },
				new Country { ID = 133, Name = "Palau" },
				new Country { ID = 134, Name = "Panama" },
				new Country { ID = 135, Name = "Papua New Guinea" },
				new Country { ID = 136, Name = "Paraguay" },
				new Country { ID = 137, Name = "Peru" },
				new Country { ID = 138, Name = "Philippines" },
				new Country { ID = 139, Name = "Poland" },
				new Country { ID = 140, Name = "Portugal" },
				new Country { ID = 141, Name = "Qatar" },
				new Country { ID = 142, Name = "Romania" },
				new Country { ID = 143, Name = "Russia" },
				new Country { ID = 144, Name = "Rwanda" },
				new Country { ID = 145, Name = "Saint Kitts and Nevis" },
				new Country { ID = 146, Name = "Saint Lucia" },
				new Country { ID = 147, Name = "Saint Vincent and the Grenadines" },
				new Country { ID = 148, Name = "Samoa" },
				new Country { ID = 149, Name = "San Marino" },
				new Country { ID = 150, Name = "Sao Tome and Principe" },
				new Country { ID = 151, Name = "Saudi Arabia" },
				new Country { ID = 152, Name = "Senegal" },
				new Country { ID = 153, Name = "Serbia" },
				new Country { ID = 154, Name = "Seychelles" },
				new Country { ID = 155, Name = "Sierra Leone" },
				new Country { ID = 156, Name = "Singapore" },
				new Country { ID = 157, Name = "Slovakia" },
				new Country { ID = 158, Name = "Slovenia" },
				new Country { ID = 159, Name = "Solomon Islands" },
				new Country { ID = 160, Name = "Somalia" },
				new Country { ID = 161, Name = "South Africa" },
				new Country { ID = 162, Name = "South Sudan" },
				new Country { ID = 163, Name = "Spain" },
				new Country { ID = 164, Name = "Sri Lanka" },
				new Country { ID = 165, Name = "Sudan" },
				new Country { ID = 166, Name = "Suriname" },
				new Country { ID = 167, Name = "Sweden" },
				new Country { ID = 168, Name = "Switzerland" },
				new Country { ID = 169, Name = "Syria" },
				new Country { ID = 170, Name = "Taiwan" },
				new Country { ID = 171, Name = "Tajikistan" },
				new Country { ID = 172, Name = "Tanzania" },
				new Country { ID = 173, Name = "Thailand" },
				new Country { ID = 174, Name = "Timor-Leste" },
				new Country { ID = 175, Name = "Togo" },
				new Country { ID = 176, Name = "Tonga" },
				new Country { ID = 177, Name = "Trinidad and Tobago" },
				new Country { ID = 178, Name = "Tunisia" },
				new Country { ID = 179, Name = "Turkey" },
				new Country { ID = 180, Name = "Turkmenistan" },
				new Country { ID = 181, Name = "Tuvalu" },
				new Country { ID = 182, Name = "Uganda" },
				new Country { ID = 183, Name = "Ukraine" },
				new Country { ID = 184, Name = "United Arab Emirates" },
				new Country { ID = 185, Name = "United Kingdom" },
				new Country { ID = 186, Name = "United States" },
				new Country { ID = 187, Name = "Uruguay" },
				new Country { ID = 188, Name = "Uzbekistan" },
				new Country { ID = 189, Name = "Vanuatu" },
				new Country { ID = 190, Name = "Vatican City" },
				new Country { ID = 191, Name = "Venezuela" },
				new Country { ID = 192, Name = "Vietnam" },
				new Country { ID = 193, Name = "Yemen" },
				new Country { ID = 194, Name = "Zambia" },
				new Country { ID = 195, Name = "Zimbabwe" }
			);

            modelBuilder.Entity<Player>().HasData(
				new Player { ID = 1, FirstName = "Michael", LastName = "Jordan", TeamID = 5, PositionID = 2, DateOfBirth = new DateTime(1963, 2, 17), Height = 198, Weight = 98, CountryID = 186 }, 
				new Player { ID = 2, FirstName = "Scottie", LastName = "Pippen", TeamID = 5, PositionID = 3, DateOfBirth = new DateTime(1965, 9, 25), Height = 203, Weight = 102, CountryID = 186 },
				new Player { ID = 7, FirstName = "Derrick", LastName = "Rose", TeamID = 5, PositionID = 1, DateOfBirth = new DateTime(1988, 10, 4), Height = 190, Weight = 89, CountryID = 186 },
				new Player { ID = 8, FirstName = "Artūras", LastName = "Karnišovas", TeamID = 5, PositionID = 4, DateOfBirth = new DateTime(1971, 12, 28), Height = 203, Weight = 108, CountryID = 101 },

				new Player { ID = 3, FirstName = "Luka", LastName = "Dončić", TeamID = 7, PositionID = 1, DateOfBirth = new DateTime(1999, 2, 28), Height = 201, Weight = 109, CountryID = 158 }, 
				new Player { ID = 9, FirstName = "Dirk", LastName = "Nowitzki", TeamID = 7, PositionID = 4, DateOfBirth = new DateTime(1978, 6, 19), Height = 213, Weight = 111, CountryID = 64 },

				new Player { ID = 4, FirstName = "Kobe", LastName = "Bryant", TeamID = 14, PositionID = 2, DateOfBirth = new DateTime(1978, 8, 23), Height = 198, Weight = 96, CountryID = 186 },
				new Player { ID = 5, FirstName = "LeBron", LastName = "James", TeamID = 14, PositionID = 3, DateOfBirth = new DateTime(1984, 12, 30), Height = 206, Weight = 113, CountryID = 186 },
				new Player { ID = 12, FirstName = "Magic", LastName = "Johnson", TeamID = 14, PositionID = 1, DateOfBirth = new DateTime(1959, 8, 14), Height = 206, Weight = 100, CountryID = 186 },
				new Player { ID = 13, FirstName = "Shaquille", LastName = "O'Neal", TeamID = 14, PositionID = 5, DateOfBirth = new DateTime(1972, 3, 6), Height = 216, Weight = 147, CountryID = 186 },

				new Player { ID = 33, FirstName = "Nikola", LastName = "Jokic", TeamID = 8, PositionID = 5, DateOfBirth = new DateTime(1995, 2, 19), Height = 208, Weight = 113, CountryID = 153 },
				new Player { ID = 34, FirstName = "Carmelo", LastName = "Anthony", TeamID = 8, PositionID = 3, DateOfBirth = new DateTime(1984, 5, 29), Height = 203, Weight = 109, CountryID = 186 }

            );

        }

	}
}
